GET http://localhost:3000/todos-lists
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjEsImlhdCI6MTY3ODcyODM0MCwiZXhwIjoxNjc4NzI4OTQwfQ.rspur_UT8VgutXeA1XAV3LFPES2aM4Mj74SMyqVQp6Y