PATCH http://localhost:3000/todos-lists/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjEsImlhdCI6MTY3ODcyODk5MiwiZXhwIjoxNjc4NzI5NTkyfQ.ZpGAKwlNOqIqJyKnAqkb9ByQW20OJnkWwq9lE6dBhHw

{
    "id": 3,
    "archived": false
}