GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoZXhlbm9ucyIsInN1YiI6NiwiaWF0IjoxNjc4NzI1ODc4LCJleHAiOjE2Nzg3MjU5Mzh9.hRoKgAUTnUqe5eVLJ0ToFAJN2wkltrfsFtc0ZVcKquQ